name: Terraform init and plan
on:
  push:
    branches:
    - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Login to Azure
      # uses: azure/login@v2
      run: |
        az login
      with:
        client-id: ${{ secrets.AZURE_CLIENTID }}
        tenant-id: ${{ secrets.AZURE_TENANTID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}
        # enable-AzPSSession: true

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Get code
      uses: actions/checkout@v3

    - name: Terraform check
      uses: actions/terraform@v2

    - name: Terraform initialize
      run: terraform init
