name: Terraform Workflow
on:
  pull_request:
    branches:
    - main
jobs:
  code-syntax:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Initialize Terraform
      run: terraform init

    - name: Syntax validation
      run: terraform validate

  terraform-plan:
    needs: code-syntax
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Azure Login
      run: |
        az login --service-principal -u "${{ secrets.AZURE_CLIENTID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANTID }}"

    - name: Initlize Terraform
      run: terraform init

    - name: Planing Phase
      run: terraform plan

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Login to Azure
      run: |
        az login --service-principal -u "${{ secrets.AZURE_CLIENTID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANTID }}"

    - name: Terraform initialize
      run: terraform init

    - name: Applying for terraform
      run: terraform apply -auto-approve
